### ISSUE TITLE
FHIR R3 Encounter participant parameter incorrectly typed

### ISSUE THREAD

**Issue by neilhsieh** [smilecdr/FHIR.ts#20]
The participant parameter in Encounter currently in FHIR.ts R3 is 

`export declare class Participant extends BackboneElement {
    type: CodeableConcept[];
    actor: Reference;
    required: string;
    status: string;
    period: Period;
}`

This is the incorrect participant parameters in the Encounter resource: http://hl7.org/fhir/STU3/encounter.html.

**Comment by omarhoblos** [comment]
Just to double check - would you like to see something like `EncounterParticipant` so it doesn't have the other types in its structure?

**Comment by neilhsieh** [comment]
That could work yup
