### ISSUE TITLE
R3 QuestionnaireResponseItem and Answer should allow nested QuestionnaireResponseItems

### ISSUE THREAD

**Issue by TahaAttari** [smilecdr/FHIR.ts#22]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/18551992/166744309-d841343a-4e9d-4539-be17-29f03dd25a3a.png">

**Comment by chisholmd** [comment]
Doesn't it?  Maybe I am reading the question wrong

**Comment by TahaAttari** [comment]
So currently these are the definitions of the `QuestionnaireResponseItem` and the `Answer` and they don't have any slot for nested items (sorry should have included these as well).
```
export declare class QuestionnaireResponseItem extends BackboneElement {
    linkId: string;
    definition: string;
    text: string;
    answer: Answer[];
}

export declare class Answer extends BackboneElement {
    valueDecimal: number;
    valueInteger: number;
    valueDate: Date;
    valueDateTime: Date;
    valueTime: string;
    valueString: string;
    valueUri: string;
    valueAttachment: Attachment;
    valueCoding: Coding;
    valueQuantity: Quantity;
    valueBoolean: boolean;
    valueReference: Reference;
}
```

**Comment by chisholmd** [comment]
Yes I see now that your were specifically talking about items under answer.
