### ISSUE TITLE
Date type should be "string", not only JS Date interface

### ISSUE THREAD

**Issue by TahaAttari** [smilecdr/FHIR.ts#25]
The FHIR basic datatypes `dateTime` and `instant` should be `Date | string` otherwise it is difficult to use other libraries / methods to create dates

**Comment by und3f** [comment]
Totally agree on this, since we receive JSON response with strings not Dates such fields should be strings. Also there is an example in R4: fhirR4.StructureDefinition.date and IfhirR4.IStructureDefinition.date

**Comment by TahaAttari** [comment]
yes for all of the properties 👍🏾
