### ISSUE TITLE
No copyright notice in project

### ISSUE THREAD

**Issue by und3f** [smilecdr/FHIR.ts#28]
There are no copyright notice in readme or source files. License file states that there should be notice in format `Copyright [yyyy] [name of copyright owner]`

**Comment by omarhoblos** [comment]
I think the intent is to add the license header to *all* files in the repo - I've seen this in a couple projects so it makes sense why it might be asked for here. However, considering we already include our LICENSE (as Aditya has pointed out earlier), it's not required for it to be appended to all source files, as the license should cover all sources in the repo

**Comment by und3f** [comment]
There should be a licensor (and it is described in Apache license) that is copyright owner. Currently project doesnt have information on who is copyright owner.
It is not necessary to include copyright notice in every file, it could be placed in readme (like here https://www.npmjs.com/package/vectorize-pixelart#copyright)

**Comment by AD1306** [comment]
Can you tell me the official source where it mentions that you absolutely need a CopyrightNotice ?

**Comment by AD1306** [comment]
Closing this as no response from the original author.
