### ISSUE TITLE
Enhancement: Resource Narrowing

### ISSUE THREAD

**Issue by TahaAttari** [smilecdr/FHIR.ts#39]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/18551992/200676538-96de316d-4974-4235-870d-de081edd20d0.png">
<img width="306" alt="image" src="https://user-images.githubusercontent.com/18551992/200676585-9efdfc34-4c19-48dc-91b3-e64c4b81d634.png">

Currently when parsing a bundle type assertions are manual, it requires a human to check that `entry.resource.resourceType` matches the type which is being asserted. [If we reorganized the definitions a little we could have this happen automatically.](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4QEoQwewFcolkBvAKGWqjyJIgBUBPABwgC4MwpQBzCgF8KoSLEQoAwnFoAFADZwQyCAA9IIACYY0mHHWJJK1ZLQKGmbTgHJpcxSGtCR4aPFKpCW+SjUbtuli45gzGNAYMLOwc1p7eEE7CYFbIwfSkALxoXpo+yAA+yHYQCkoUMF4IYMD4ynwQYGkWURAAFGYcTQwAlGHIwDDteAB0ZumW7MgZ08i2MiUO1r1UJuEYK8iCyM5AA) as can be seen in the screenshots and the playground link.

EDIT2: Ok updated the playground link now it works

**Comment by AD1306** [comment]
resolved in #40
