### ISSUE TITLE
Error Deserializing Patient Resource

### ISSUE THREAD

**Issue by matttsai-orx** [smilecdr/FHIR.ts#84]
## Description
When following the instructions in the FHIR.ts Getting Started guide, I encountered an error related to deserializing a Patient resource. The specific error message is:
`Error deserializing Patient resource: TypeError: resourceUtils.deserializedPatientResource is not a function`

## Steps to Reproduce
1. Navigate to the Getting Started guide.
2. Follow the provided code examples for initializing a Patient resource.
3. Observe the error mentioned above.

## Expected Behavior
The Patient resource should be successfully deserialized without any errors.

## Additional Context
- Using FHIR.ts library.
- The issue occurs during resource deserialization.
- I've tried FHIR R4 libraries.

**Comment by AD1306** [comment]
Hello @matttsai-orx, that function doesn't exist and might've been leftover during some cleanup. Apologies for that. For your solution you can actually just use type assertion : https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions  

Example: 
```ts
const patient = object as Patient;
```
