### ISSUE TITLE
BundleUtils.getBundleEntryByReference

### ISSUE THREAD

**Issue by maxi-smidt** [smilecdr/FHIR.ts#95]
I have a project where we need a function like this: 
getBundleEntryByReference = (bundleEntry: any[], reference: string) {
    return bundle?.entry?.find((x) => x['fullUrl'] === reference);
};

if you think this function could be useful for this project too, I could include it. 

Another question I have, are the functions in the BundeUtils are called getResource(s) but both of them return a BundleEntry, not a resource. Am I missing something or is this a mistake?

Thanks!

**Comment by AD1306** [comment]
Hello @maxi-smidt,

Sure that sounds reasonable. Feel free to create a PR for that. 

Yes, atm `BundleUtils` methods do return `BundleEntry` but it might infact make more sense to return resources. I'm on opposed to that.

Thanks !

**Comment by maxi-smidt** [comment]
@AD1306 there is a pr now for it #96
